channels:
  - conda-forge
dependencies:
  - python >=3.8, <3.11
  - numpy
  - xarray
  - matplotlib
  - seaborn
  - bioformats_jar
  - napari
  - pyqt
  - scikit-image
  - pip
  - pip:
    - aicsimageio
    - aicsimageio[nd2]
    - aicsimageio[base-imageio]
    - -e .