name: bim_xarray
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - ipykernel
  - pytest

# scientific python stack
  - xarray
  - dask
  - matplotlib
  - seaborn

# image viewing and processing
  - bioformats_jar
  - napari
  - pyqt
  - scikit-image

# pip installed
  - pip
  - pip:
    - aicsimageio
    - aicsimageio[nd2]
    - aicsimageio[base-imageio]
    - "ome-types>=0.3.4,<0.4.0"
    - -e .